[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
{{ commit.message | split(pat="\n") | first | upper_first | trim }}\
{% if commit.breaking %} **BREAKING**{% endif %} \
([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/fogrew/fontstay.dev/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}
"""
footer = """
{% for release in releases -%}
{% if release.version -%}
{% if release.previous.version -%}
[{{ release.version | trim_start_matches(pat="v") }}]: https://github.com/fogrew/fontstay.dev/compare/{{ release.previous.version }}...{{ release.version }}
{% else -%}
[{{ release.version | trim_start_matches(pat="v") }}]: https://github.com/fogrew/fontstay.dev/releases/tag/{{ release.version }}
{% endif -%}
{% else -%}
{% if release.previous.version -%}
[Unreleased]: https://github.com/fogrew/fontstay.dev/compare/{{ release.previous.version }}...HEAD
{% else -%}
[Unreleased]: https://github.com/fogrew/fontstay.dev/commits/develop
{% endif -%}
{% endif -%}
{% endfor %}
"""
trim = false

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "newest"
commit_parsers = [
  { message = "^chore\\(release\\)", skip = true },
  { scope = "security", group = "<!-- 5 -->Security" },
  { scope = "deprecate", group = "<!-- 2 -->Deprecated" },
  { message = "^feat", group = "<!-- 0 -->Added" },
  { message = "^(refactor|perf|style)", group = "<!-- 1 -->Changed" },
  { message = "^revert", group = "<!-- 3 -->Removed" },
  { message = "^fix", group = "<!-- 4 -->Fixed" },
  { message = "^(docs|test|build|ci|chore)", skip = true },
]
